### ISSUE TITLE
Reviewer 3 rewrite checklist

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-paper#207]
_Adding this as a seperate issue from https://github.com/sympy/sympy-paper/issues/204._

The paper introduces SymPy, a well-known pure Python library for symbolic computation. It covers many aspects of the library: architecture, basic usage, overview of modules, a more detailed look into some of them, and physics application.

The writing style is mostly clear and easy to understand. Some example code is provided to further explain the use of various module, classes, and functions. Unfortunately, the paper is very unconnected and disorganized, with some unnecessary repetition and some things left undefined. Further, parts of the supplement should be moved to the main paper and vice versa. All of this makes the paper look more like a collection of unconnected or, at best, very
loosely connected parts, instead of a meaningful whole.

Another big problem of the paper is the lack of aim. Some parts of SymPy
are covered at informative level (short descriptions of the elements related to some subject), some at the beginners level (basic usage examples), while some go deep in internal SymPy implementation of certain features. This structure leaves the impression that different, yet mutually intermingled sections aim at different audiences.

Moreover, these vastly differently approached elements come in no specific order, and with no obvious reason why each of them is picked to be covered at all and, specifically, at the chosen level of complexity in the approach.

I suggest a major rewrite of the paper, to improve the structure and group differently approached subjects. It would probably be best to:
- [ ] 1. Create a new section (following the introduction of SymPy) on projects that use SymPy, and put in it the materials currently available in supplement’s sections 8, 9, 11. The comparison with Mathematica (supplement’s section 10) should be moved either to the introduction as a section, or right after the introduction as its own section, but it should not be in the middle of the description of SymPy-powered projects.
- [ ] 2. This should be followed by the list of SymPy packages and modules (currently section 3) and descriptions of selected modules (currently sections 3.1, 3.3, 3.5, supplement’s sections 5, 7, and 9).
- [ ] 3. Now, basic usage can be given as its own section (currently done in sections 2.1 and 2.3), followed by introductions on usage of various modules (currently in sections 3.2, 3.4, 3.6, 4, 5, and supplement’s sections 2, 3, 4, 6).
- [ ] 4. In-depth architecture (most of the so far unmentioned sections) can be given either as its own section, or made into a supplement of its own (as it is naturally far more technical and less interesting to general audience).
- [ ] 5. The current conclusion works fine as the finishing section of the paper.

The suggested reorganization still leaves the paper unbalanced with respect to which SymPy features are covered and in how much detail. I suggest that the authors expand the sections that are currently only descriptive. Further, some motivation should be given for the choice of the features that are explained (as opposed to just being listed in what is currently section 3).

**Comment by asmeurer** [comment]
I would love to hear other people's opinions on this. My initial thoughts:
- One of the main themes of the paper is to be about the architecture of SymPy. So I feel that demoting that section in importance goes against the purpose of the paper. 
- The comparison with Mathematica was left out of the main paper intentionally because it is biased. We lack comparisons to other CASs and the expertise to write them. Also, I see no reason to assume that the typical reader of the paper will have a knowledge of Mathematica as a background (the background for the paper already assumes Python knowledge). 
- I agree that the ordering of the sections in the supplement can be improved.  
- SymPy has a lot of features (c.f. the features table). To discuss them all equally would double the size of the current paper + supplement. The main paper focuses on those features that are considered core to SymPy, and a select set of additional features are treated in the supplement.

**Comment by scopatz** [comment]
> The comparison with Mathematica was left out of the main paper intentionally because it is biased. We lack comparisons to other CASs and the expertise to write them. Also, I see no reason to assume that the typical reader of the paper will have a knowledge of Mathematica as a background (the background for the paper already assumes Python knowledge).
> 
> SymPy has a lot of features (c.f. the features table). To discuss them all equally would double the size of the current paper + supplement. The main paper focuses on those features that are considered core to SymPy, and a select set of additional features are treated in the supplement.

I think that these are important point to make in the response to the editor.

**Comment by certik** [comment]
@asmeurer I actually like the reviewer's suggestions in general. I think it would make the paper more accessible and more readable for a general audience. Regarding your points:

> One of the main themes of the paper is to be about the architecture of SymPy. So I feel that demoting that section in importance goes against the purpose of the paper. 

There could still be a section about the architecture of sympy in the main paper. I don't think it necessarily must be the only main purpose of the paper.

> The comparison with Mathematica was left out of the main paper intentionally because it is biased. We lack comparisons to other CASs and the expertise to write them. Also, I see no reason to assume that the typical reader of the paper will have a knowledge of Mathematica as a background (the background for the paper already assumes Python knowledge). 

That's a good point and we don't need the Mathematica comparison in the main paper.

> I agree that the ordering of the sections in the supplement can be improved. 

And also the main paper.

> SymPy has a lot of features (c.f. the features table). To discuss them all equally would double the size of the current paper + supplement. The main paper focuses on those features that are considered core to SymPy, and a select set of additional features are treated in the supplement. 

The reviewer doesn't suggest to discuss all features equally well: _I suggest that the authors expand the sections that are currently only descriptive. Further, some motivation should be given for the choice of the features that are explained (as opposed to just being listed in what is currently section 3)._ As you can see, the reviewer is just asking to explain how we chose the features that we explain in detail. So we just put there a paragraph along the lines: sympy's main features are X, Y, Z, .. and below we discuss those in more detail. The rest of the features are only briefly mentioned in the table, the reader can read more about those in SymPy's documentation.

**Comment by asmeurer** [comment]
One must also consider the logical progression of the sections if the architecture section comes before or after the features sections. It is written right now in a way that makes sense for the current ordering.

**Comment by asmeurer** [comment]
So we'll need to read the paper carefully, but I think that if we split out basic usage and assumptions from architecture, then nothing else in the architecture section is referenced later on. As far as I can tell, you don't need to know the details of the core (`.args`, expression trees), or the details of the extensibility (`Basic`, `Expr`, `Function`, special methods) to understand the later sections, but it should be double checked. 

So it could be moved to a later location in the paper. The assumptions section is currently somewhat technical, as it fits both the "usage" and "architecture" roles, so it would need to be split.
